sudo: false
language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "stable"
  - "4"
  - "0.12"
before_install:
  - sudo apt-get install libpoppler-cpp-dev
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
